### ISSUE TITLE
Error using hyperref

### ISSUE THREAD

**Issue by VKphysics** [vtex-soft/texsupport.elsevier-book#14]
LaTeX compilation fails when the command \usepackage{hyperref} is added at the end of the preamble in the \documentclass{elsevierbook}, also with the option [a02]. System: Mac OS 10.14.6, pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020), kpathsea version 6.3.2. 

The attached file is the complete book template as it came with the only addition in the lines 31 -- 36 where this problem is described. 

Thank you for help in advance. 
[Template_LaTeX.zip](https://github.com/vtex-soft/texsupport.elsevier-book/files/6217871/Template_LaTeX.zip)

**Comment by dgalcius** [comment]
Thanks for the report. The current class doesn't support {hyperref} package.  I will add it on todo list. It won't be quick fix.

**Comment by dgalcius** [comment]
I have updated the style. Please update your sty/ files from the repo. 
Thanks.
