### ISSUE TITLE
No file OMLntxmi.fd.  ! LaTeX Error: This NFSS system isn't set up properly.

### ISSUE THREAD

**Issue by Shengjie-Xu** [vtex-soft/texsupport.elsevier-book#17]
Hi - I have the following question when I used the elsevier-book template in Ctex. 
Looking forward to your reply. Thank you very much.

LaTeX Font Warning: Font shape `T1/ntxtlf/m/n' undefined
(Font)              using `T1/cmr/m/n' instead on input line 39.

(C:\Users\13686823249\Music\Desktop\elsevierbook-project-template\book.aux)
No file OMLntxmi.fd.

! LaTeX Error: This NFSS system isn't set up properly.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

**Comment by dgalcius** [comment]
Hi, - thank you for the issue report. I'm afraid, I know nothing about ctex. I won't be able to help you much. 

I tried to load {ctex} package (`\usepackage[UTF8]{ctex}`)and it did compile fine with lualatex compiler, but not with pdflatex .
I'm using the latest TeXlive distribution (TeXive 2022) on Linux. Inspecting .fls file (set  `--recorder` option to get  it)
I can see that latex found   `omlntxmi.fd` (not `OMLntxmi.fd`) file
`INPUT /usr/local/texlive/2222/texmf-dist/tex/latex/newtx/omlntxmi.fd`
The  same for `kpathsea`. `$ kpsewhich omlntxmi.fd` command can find the file, but not  `$ kpsewhich OMLntxmi.fd`.

My suggestion would be to try to update the LaTeX distribution you are using (or use the latest one) and use 
`lualatex` compiler.  Alternatively, you can drop the elsevierbook template altogether,
and use the one you are most comfortable working with or  one that works with {ctex}. 

best regards, - deimi

**Comment by Shengjie-Xu** [comment]
Thank you very much.

**Comment by Shengjie-Xu** [comment]
Hi - I have another question when I use the template.

I use the code:
\section{The model \eqref{A} for the model \eqref{B}}

However, the results display that
"THE MODEL (??) FOR THE MODEL (??)"

So why does the code \eqref{} has no effect in the code \section{}? How to tackle it?

Looking forward to your reply. Thank you very much.

**Comment by dgalcius** [comment]
`\eqref{A}` is a reference to am equation with a label `\label{A}`.  You have to label equation(s) first in order to get a reference to it. E..g, the following works as expected:
```
\section{The model \eqref{A} for the model \eqref{B}}

\begin{equation}
  x + y \label{A}
\end{equation}

\begin{equation}
  x + z \label{B}
\end{equation}
```

best regards, - deimi

**Comment by Shengjie-Xu** [comment]
Thanks for your helpful suggestion.

I have defined \label{A} first, but it is still an error.

Code:
\section{Primal-dual extension of the ADMM \eqref{Eq-ADMM} for the model \eqref{Problem-IneC}} 

Display:
PRIMAL-DUAL EXTENSION OF THE ADMM (??) FOR THE MODEL (??)
