### ISSUE TITLE
\ref{} does not work in \section{} 

### ISSUE THREAD

**Issue by Shengjie-Xu** [vtex-soft/texsupport.elsevier-book#18]
I have the following question:

Code:
\section{Primal-dual extension of the ADMM \eqref{Eq-ADMM} for the model \eqref{Problem-IneC}}

Display:
PRIMAL-DUAL EXTENSION OF THE ADMM (??) FOR THE MODEL (??)

I have defined these \label first, but it does not still work.

Thanks for your great help.

**Comment by dgalcius** [comment]
Please can you provide with MWE (minimum (non-)working example) - tex file, that I can run/check on my system?

**Comment by Shengjie-Xu** [comment]
Dear Deimantas，
&nbsp; &nbsp;
Please see the attachments for the MWE latex files (main.tex in Handbook-Style.zip) and the display result (Display-result.pdf). These files are conducted in a Overleaf online environment. Thank you very much.




Best regards, Shengjie&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, May 21, 2022 09:53 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [vtex-soft/texsupport.elsevier-book] \ref{} does not work in \section{}  (Issue #18)

&nbsp;



 
Please can you provide with MWE (minimum (non-)working example) - tex file, that I can run/check on my system?

**Comment by dgalcius** [comment]
Unfortunately, the github drops all the attachments. Perhaps you could put the zip file on the internet (eg. dropbox or google drive), and share a link with me? thank you - deimi

**Comment by Shengjie-Xu** [comment]
I have another way. Using the standard template [elsevierbook-project-template], I addtioanally add the following codes in [chapter1.tex]:

\section{Section title}\label{sec1}
\begin{equation}\label{Model}
\min{f_1(x)+f_2(y) \;|\; Ax+By=b}    
\end{equation}
\section{Analysis for the model \eqref{Model}}

However, the display result for [\section{Analysis for the model \eqref{Model}}] is 
[1.2 ANALYSIS FOR THE MODEL (??)]

Thank you very much.

**Comment by dgalcius** [comment]
Thank you - I see the issue. Will look into it.

**Comment by dgalcius** [comment]
I have updated the style files. Please update your `sty/` folder from
https://github.com/vtex-soft/texsupport.elsevier-book/tree/master/sty page.

The problem lies in `\section` being printed in uppercase letters with `\MakeUppercase` macro which makes label (Model) to 
be uppercase too. I have substituted `\MakeUppercase` into `\MakeTextUppercase` which fixes `\ref` labels, but not `\eqref`. 
Therefore, please update style files and change `\eqref{Model}` into `(\ref{Model})` in `\section` titles.

Thank you &
kind regards, - deimi

**Comment by Shengjie-Xu** [comment]
Thanks for your great help. I have solved this issue successfully.
