### ISSUE TITLE
Capitalization in elsarticle-num

### ISSUE THREAD

**Issue by ukd** [vtex-soft/texsupport.elsevier-book#19]
The first character in “note” fields is forced to lower case. This is almost always a mistake.

In article titles lower case in enforced in inline equations ($…$).

In article titles lower case is enforced even after full stops.  This turns titles like “… equilibrium calculations. III. Algorithms” into
“… equilibrium calculations. iii. algorithms”

This misbehavior can, of course, be turned off by enclosing everything in braces, but I would prefer an improvement of the bibstyle over modifying my literature data base.

**Comment by dgalcius** [comment]
Hi, thanks for the issue report. I will look into it.

**Comment by dgalcius** [comment]
The "note" field is in lowercase as it is preceded with a comma, not a full stop.
The  "title" field is in lowercase (in math and after period) as the `change.case$`
transformation is applied.
As you say, it's a common way to control capitalization (and sorting) with 
additional braces `{}`. So, please use the braces if appropriate.

I do not find anything wrong with the style itself.
Closing.
