### ISSUE TITLE
Only one Chapter Author

### ISSUE THREAD

**Issue by katyhuff** [vtex-soft/texsupport.elsevier-book#2]
I am authoring a chapter using the elsevierbook class. I can't seem to have just one author.

With the following code (and many other variations):

```tex
\begin{aug}
        \setcounter{augtemp}{0}
       \author[addressrefs={ad1}]{\fnm{Kathryn D.} \snm{Huff}}
\address[id=ad1]{Department of Nuclear, Plasma, and Radiological Engineering\\
  104 S. Wright Street\\
  MC-234\\
  Urbana, IL 61801}
\end{aug}
```

I get this:
![image](https://user-images.githubusercontent.com/393899/36863028-2b17145e-1d4e-11e8-91b7-fc3c01da152a.png)

No matter what I do, it won't just put one author there without the comma and the and. 
What's the deal?

**Comment by dgalcius** [comment]
Thank you for the report. I've just uploaded new version. Please can you check it with new class version?

**Comment by katyhuff** [comment]
Sorry for the delayed response -- worked great ! 
![image](https://user-images.githubusercontent.com/393899/38771761-849ea272-3fee-11e8-99fd-2a5febdca66b.png)
