### ISSUE TITLE
Appendix labeling in Book Draft "Visualizing More Quaternions" is a train wreck...

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#20]
AND Hi again -- I finally got the Appendices to renumber correctly.
I think I may have omitted some Appendix inconsistently using \includeonly
and that fouled it up, not the sectionappendix.

     So, you can close out this issue -- I figured it out, finally, after
a couple of months of puzzlement.
    Thanks, Andy

PS - if there is a better way to make additions to an open issue thant
this "edit" options, PLEASE teach me how to do it!

  
---------

Hi again  - Oct 8 2022:  Sorry, this interface is very strange for me.
I've been trying for a long time to see how to add another piece to
this thread, and I can't see anything at all that looks like a "reply".
    So I'm editing the existing comment at the top.  I really don't
understand how I'm supposed to use this - you told me to use
this instead of email, but there is no button that allows adding
a new box of information without messing with the original?
    Anyway, the ridiculous misformatting and numbering of the
Appendices is really bugging me as I start to put the book
in final-draft shape over the next few weeks, and I have an
hypothesis:  You gave me a method to add "Chapter-wise
appendices", which I think make a lot of sense in several chapters.
But the main-book appendices are starting with  E, F ... and worse,
instead of A,B,C,D,... as they are in my previous book templates.
I have just enough Chapter Appendices (all correctly labeled
by the way) to get down to "F" if they incorrectly incremented
the GLOBAL label counter.  Can you duplicate that by looking
at how your Chapter-Appendix thingy works?  That might need
additional coding, might get rid of the train wreck...

\sectionappendix
 
\section{ABC}

blah blah

%% NEED ALSO THIS  - \sectionappendix kills all the later chapter section numbers,  
%%     - must add this to the end of the chapter after all the appendices:
 
\appto\frontmatter{\gdef\thesection{\thechapter.\arabic{section}}}

is what I do for a Chapter appendix list of \section 's , where my header.tex file says:

%% Special Chapter Appendix, provided by VTeX

\newcommand*\sectionappendix{%
  \par\setcounter{section}{0}%
  \setcounter{subsection}{0}%
  \gdef\thesection{\thechapter.\Alph{section}}%
}

Best, Andy

    

<Sept 4 2022>
Hi - we've corresponded about this before, but as I get closer to completion of the book draft, the disastrous labeling of the Appendices is annoying when I try to see, for example, if a given chapter's reference to an Appendix at the end of the book is even close to correct.  Attached is what I see in the Index, and in the actual labeling of equations and sections in the Appendices themselves.   I have tried a number of ways to try to identify what is going on, but have so far met with complete failure to understand this phenomenon.
  
   If you can't do anything until you get the whole book, we can of course deal with that.  But if it could be fixed while I'm doing all this writing and cross-checking, that would be better!
   Thanks, Andy Hanson

![image](https://user-images.githubusercontent.com/13339899/188327571-72f726ef-fee9-49ee-9f01-794d4a5188da.png)
![image](https://user-images.githubusercontent.com/13339899/188327606-20f0d8de-9e5d-4b20-8794-738e29d5af8a.png)

**Comment by dgalcius** [comment]
Hi, thanks for the issue report. 
I cannot reproduce it. 
With the code 
```
\begin{document}
\Frontmatter
\begin{frontmatter}
\chapter*{Contents}
\end{frontmatter}

\tableofcontents

\Mainmatter
\begin{frontmatter}
\chapter{Chapter One title}
\end{frontmatter}

\section{section title}

\sectionappendix
 \section{Appendix section title}

\begin{frontmatter}
\chapter{Chapter Two title}
\end{frontmatter}

\section{section title}

\appendix

\begin{frontmatter}
\chapter{Appendix A title}
\end{frontmatter}

\section{Appendix A section title}


\begin{frontmatter}
\chapter{Appendix B title}
\end{frontmatter}

\section{Appendix B section title}

\Backmatter
\end{document} 
```
I get an output which seems to be ok. 

![image](https://user-images.githubusercontent.com/10126095/188442481-f7006374-f0c1-4213-a73c-47201993dfbe.png)

Could you provide with MWE with the issue that I could work on? 

thanks, deimi

**Comment by andjorhanson** [comment]
Hi - Thanks for trying.  It will take some effort to narrow down the
code to an excerpt that has the effect - it persists even if I change
"\includeonly{}" to very small numbers of files, and no appendices
being recompiled at all.  But if I add any single Appendix to includeonly,
the actual typeset text has all the same wrong ABCDEFG labels as
the index.  I will put this on my todo list, may not get to it right away -
I guess I was hoping you'd seen this a dozen times and would know
exactly where the weak spot was!
  Best, Andy


On Sep 5, 2022, at 7:54 AM, Deimantas Galčius ***@***.******@***.***>> wrote:



Hi, thanks for the issue report.
I cannot reproduce it.
With the code

\begin{document}
\Frontmatter
\begin{frontmatter}
\chapter*{Contents}
\end{frontmatter}

\tableofcontents

\Mainmatter
\begin{frontmatter}
\chapter{Chapter One title}
\end{frontmatter}

\section{section title}

\sectionappendix
 \section{Appendix section title}

\begin{frontmatter}
\chapter{Chapter Two title}
\end{frontmatter}

\section{section title}

\appendix

\begin{frontmatter}
\chapter{Appendix A title}
\end{frontmatter}

\section{Appendix A section title}


\begin{frontmatter}
\chapter{Appendix B title}
\end{frontmatter}

\section{Appendix B section title}

\Backmatter
\end{document}


I get an output which seems to be ok.

[image]<https://user-images.githubusercontent.com/10126095/188442481-f7006374-f0c1-4213-a73c-47201993dfbe.png>

Could you provide with MWE with the issue that I could work on?

thanks, deimi

**Comment by andjorhanson** [comment]
See notes -- I figured it out!  This works now so you can close this.
   I was very puzzled about the interface, and left EDITS instead of comments
because this  COMMENT bar was scrolled so many pages down I never saw
it until accidentally JUST this minute after adding several edits to the main text.
    Anyway, I found the  Comment, I fixed the problem, and this can be closed.
    THanks so much!
  Andy
