### ISSUE TITLE
Question about font warnings

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#21]
Hi again-
   I am starting on a chapter that integrates historical lecture material of mine, with quite
a number of hard-to-replicate figures that I am using from the slides.   I get
about 100 warning messages in the pattern of those at the end of this \includeonly{} compilation:

[466] (./book.aux (./titlepage.aux) (./dedication.aux) (./preface.aux)
(./aboutauthors.aux) (./DraftOutline.aux) (./part1.aux) (./basicintro.aux)
(./basics.aux) (./whatarequats.aux) (./whatisquatvis.aux)
(./basicinteraction.aux) (./chapterQuatdatadist.aux) (./partRMSD.aux)
(./chapter2DRMSD.aux) (./chapter3DRMSD.aux) (./chapter3DRot2Quat.aux)
(./chapter3DFrames.aux) (./chapter4DRMSD.aux) (./chapterAdjugate.aux)
(./chapterMatchPose2D.aux) (./chapterMatchPose.aux) (./chapterQRotLearning.aux)
(./part2.aux) (./chapterQuatProt.aux) (./part3.aux)
(./chapterQuatDistributions.aux) (./chapterEucBary.aux) (./mychapter3BF.aux)
(./chapterQuatShading.aux) (./chapterDualQuats.aux) (./partLorentz.aux)
(./chapterLorentzIntro.aux) (./chapterLorentzViz.aux)
(./chapterRelativisticTop.aux) (./chapterTwistor.aux) (./partPhysics.aux)
(./chapterQuantumComputing.aux) (./chapterDiscreteGroups.aux)
(./chapterEHembed.aux) (./appendixNotation.aux) (./appendixCodeRotToQuat.aux)
(./appendixRInvarEig.aux) (./appendixCardano.aux) (./appendixQP.aux)
(./appendixLeviCivita.aux) (./appendixNDimGeom.aux) (./appendixIdentities.aux)
(./appendixQuatMethods.aux) (./appendixAB.aux)) )
(see the transcript file for additional information)
Output written on book.dvi (134 pages, 542072 bytes).
SyncTeX written on book.synctex.gz.
Transcript written on book.log.
### /Library/TeX/texbin/dvips -R -Poutline  -o /tmp/altpdflatex.98519-1662505516/book.ps book.dvi
This is dvips(k) 5.997 Copyright 2017 Radical Eye Software (www.radicaleye.com)
' TeX output 2022.09.06:1905' -> /tmp/altpdflatex.98519-1662505516/book.ps
/Library/TeX/texbin/dvips: Font Helvetica-Bold used in file imgRel1/tmhyp0.eps is not in the mapping file.
/Library/TeX/texbin/dvips: Font Courier used in file imgRel1/tmhyp0.eps is not in the mapping file.
/Library/TeX/texbin/dvips: Font Helvetica-Bold used in file imgRel1/tmhyp0.1.eps is not in the mapping file.
/Library/TeX/texbin/dvips: Font Courier used in file imgRel1/tmhyp0.1.eps is not in the mapping file.
/Library/TeX/texbin/dvips: Font Helvetica-Bold used in file imgRel1/tmhyp0.5.eps is not in the mapping file.
/Library/TeX/texbin/dvips: Font Courier used in file imgRel1/tmhyp0.5.eps is not in the mapping file.
....
....

   Is this serious, or can it be ignored, or, better, dealt with and fixed?   I think these are mostly
files built with an old version of Unix Xwindows "xfig".  I have a nice current working version,
which seems to make figures without complaints, but I think the font systems have changed,
or maybe I am using different fonts in the current figures.

    Ideas, suggestions, fixes?

Thanks, Andy

**Comment by dgalcius** [comment]
Hi, Andy,
these messages mean that EPS files does not have embedded fonts but rather references to the fonts. 
Please check if the pdf output is correct. As long as it is standard Postscript fonts (Times, Helvetica, Courier, Symbol) the postscript interpreter (e.g. ps2pdf) should produce a decent output. 
You can ignore warnings if the output is correct. 

If the pdf output is invalid few options comes to my mind: 
1. reinterpret/save eps files. E.g., `eps2eps` can fix some eps files. It embeds non standard fonts, but leaves references to standard ones. Other programs are Adobe Illustrator or Inscape. 
2. try to pass `-j0` option to dvips. Some people have reported that it helped. But I cannot confirm this.

I hope your pdf output is correct and you do not have to do anything about it. 

best, deimi
