### ISSUE TITLE
Caption fontsize for subfigures

### ISSUE THREAD

**Issue by ukd** [vtex-soft/texsupport.elsevier-book#22]
I typeset subfigures with the "subcaption" package. The typical code is
```
\begin{figure}
\begin{subfigure}{\textwidth}
\includegraphics …
\caption{Caption of Subfigure A.}
\end{subfigure}
…
\caption{Main caption.}
\end{figure}
```
The main caption is then typeset with a footnotesize font. The subfigure captions, however, with a normal font. Can this be changed?
Adding "\captionsetup[sub]{font=footnotesize}" to the preamble does not help.

**Comment by dgalcius** [comment]
Hi, please use 

```
\captionsetup[subfigure]{font+={footnotesize}}%       for a02  model
\captionsetup[subfigure]{font+={figcaptionfont-p04}}% for p04  model
\captionsetup[subfigure]{font+={small}}%              for a08a model
```
