### ISSUE TITLE
\sum changed to giant square root??

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#24]
Suddenly my Mac TeXShop has replaced all my \sum  math summation symbols by ENORMOUS square root signs.  I don't think I touched any macros.  Any idea what this could be?
  Best, Andy
[SumIsSqrtp19.pdf](https://github.com/vtex-soft/texsupport.elsevier-book/files/10149973/SumIsSqrtp19.pdf)
SumIsSqrtp19.pdf

**Comment by dgalcius** [comment]
Could you provide with a MWE and it's log file?

**Comment by andjorhanson** [comment]
Hi (Note - somehow my mailer has been telling you to use my personal ***@***.******@***.***>
email, when I was TRYING to use my work ***@***.******@***.***> account for Elsevier
communications -- it's fine, I read both accounts regularly, but I try to keep my folder for
these emails on hansona.)

    So - I ran a minimal version (as I should have done originally), and it is YOUR addition
to my "header.tex" file that is causing  \sum -> giant 'sqrt', and also \int -> giant '<' !

    If I remove this section from my header.tex the broken \sum and \int go away:

%% VTeX recommends instead of \overbar:
%% yhmath package version:
% USAGE: $\compositeaccents\wideparen{\Vec{v}{1} \Vec{v}{2}}$
%% replaces  \overbar{\$Vec{v}{1} \Vec{v}{2}$}

\let\widering\relax
\RequirePackage{yhmath}
\newsavebox{\accentbox}
\newcommand{\compositeaccents}[2]{%
  \sbox\accentbox{$#2$}#1{\usebox\accentbox}}


      So how do I get the "long over-arc" for  \overbar{\$Vec{v}{1} \Vec{v}{2}$} without
trashing these (and probably many other) math symbols?

   Best, Andy


On Dec 5, 2022, at 12:43 AM, Deimantas Galčius ***@***.******@***.***>> wrote:



Could you provide with a MWE and it's log file?

**Comment by andjorhanson** [comment]
Note: I just realized that an OLD github project of mine had me listed with the email address that has been used by github for you to send me emails.   I just figured out how to add my work email as "primary" and so that should work now.  I don't think you had any control over it, as it was automatic in github to use one or the other.

**Comment by dgalcius** [comment]
Please can you provide with your minimal version (+ log file), that I could run on my machine. Thanks.

**Comment by andjorhanson** [comment]
Yes --
 % ls Bug*
Bug-Sum.tex
Bug-header.tex
Bug-Sum.log
Bug-Sum.pdf

 and the class is in sty/elsevierbook-p04.cls

Search in Bug-header.tex  for the word "BUG", which precedes the troublesome
macro; removing this restores the correct  "sum" and "int" etc.

%% BUG IS HERE - remove to make \sum work again

%% VTeX recommends instead of \overbar:
%% yhmath package version:
% USAGE: $\compositeaccents\wideparen{\Vec{v}{1} \Vec{v}{2}}$
%% replaces  \overbar{\$Vec{v}{1} \Vec{v}{2}$}

\let\widering\relax
\RequirePackage{yhmath}
\newsavebox{\accentbox}
\newcommand{\compositeaccents}[2]{%
  \sbox\accentbox{$#2$}#1{\usebox\accentbox}}


However, WITHOUT this macro, my usage  $\compositeaccents\wideparen{\vec{v}_{1} \vec{v}_{2}}$
to create math overbars relating two vectors fails.

Best, Andy



On Dec 5, 2022, at 2:03 PM, Deimantas Galčius ***@***.******@***.***>> wrote:



Please can you provide with your minimal version (+ log file), that I could run on my machine. Thanks.

**Comment by dgalcius** [comment]
Please upload a zip file online (dropbox or wetransfer or any other service will do) and 
post a link. Thanks.

**Comment by andjorhanson** [comment]
?  I posted the files directly on github, or so I thought.  Anyway, here are the same files
as a Dropbox link:

https://www.dropbox.com/s/vcmlpzhtgk6a4sw/Bug-sum.zip?dl=0

% unzip -l Bug-sum.zip
Archive:  Bug-sum.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    17859  12-06-2022 00:38   Bug-Sum.pdf
     1705  12-06-2022 00:38   Bug-Sum.tex
    11901  12-06-2022 00:38   Bug-header.tex
    37894  12-06-2022 00:38   elsevierbook-p04.cls
---------                     -------
    69359                     4 files




On Dec 5, 2022, at 11:56 PM, Deimantas Galčius ***@***.******@***.***>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.



Please upload a zip file online (dropbox or wetransfer or any other service will do) and
post a link. Thanks.

**Comment by andjorhanson** [comment]
Forgot the log file:

https://www.dropbox.com/s/k8oo1x224aatauo/Bug-Sum.log?dl=0



On Dec 5, 2022, at 11:56 PM, Deimantas Galčius ***@***.******@***.***>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.



Please upload a zip file online (dropbox or wetransfer or any other service will do) and
post a link. Thanks.

**Comment by dgalcius** [comment]
Thank you for the files. 
Compiling with TeXLive 2022 or 2019 I have correct output. 
From the log file I can see, that you are using TeXLive 2017. I don't have TL2017, I cannot test it with TL2017.
However, compiling with TeXLive 2016 I have the same invalid output you have. 

I have posted two solutions for "wideparen" macro:  _fourier_ version and  _yhmath_ version. The  _fourier_ version works with TeXLive 2016 (hopefully it does with TL2017 as well). 

Reposting _fourier_ version:

    \DeclareFontEncoding{FMX}{}{}
    \DeclareFontSubstitution{FMX}{futm}{m}{n}
    \DeclareSymbolFont{fourierlargesymbols}{FMX}{futm}{m}{n}
    \DeclareMathAccent{\wideparen}{\mathord}{fourierlargesymbols}{148}
    \newsavebox{\accentbox}
    \newcommand{\compositeaccents}[2]{%
      \sbox\accentbox{$#2$}#1{\usebox\accentbox}}

Please replace _yhmath_ version with the code above.

kind regards, - deimi

**Comment by andjorhanson** [comment]
Always something that goes wrong with versions…. mine supposedly updates automatically, but I guess not enough
     Thanks, Andy


Sent from my iPhone X

On Dec 6, 2022, at 11:04 AM, Deimantas Galčius ***@***.***> wrote:

﻿
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Thank you for the files.
Compiling with TeXLive 2022 or 2019 I have correct output.
From the log file I can see, that you are using TeXLive 2017. I don't have TL2017, I cannot test it with TL2017.
However, compiling with TeXLive 2016 I have the same invalid output you have.

I have posted two solutions for "wideparen" macro: fourier version and yhmath version. The fourier version works with TeXLive 2016 (hopefully it does with TL2017 as well).

Reposting fourier version:

\DeclareFontEncoding{FMX}{}{}
\DeclareFontSubstitution{FMX}{futm}{m}{n}
\DeclareSymbolFont{fourierlargesymbols}{FMX}{futm}{m}{n}
\DeclareMathAccent{\wideparen}{\mathord}{fourierlargesymbols}{148}
\newsavebox{\accentbox}
\newcommand{\compositeaccents}[2]{%
  \sbox\accentbox{$#2$}#1{\usebox\accentbox}}


Please replace yhmath version with the code above.

kind regards, - deimi
