### ISSUE TITLE
Sanity check on Visualizing More Quaternions log file?

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#25]
Hi!
    I think I am doing pretty well on the draft of Visualizing More Quaternions.  No obvious anomalies, and I am targeting March 5 as a "ready for my final edits" draft, and
no later than April 3 for submission to my newly appointed editor,
  Andrea Gallego Ortiz  a.gallegoortiz@elsevier.com.

Now that I seem to have figured out this Github interface to ask questions, I hope, in reciprocation, that (assuming you will be preparing the book after I send it to Andrea) you will do the same, and let me participate in decisions that might affect the style and readability of the book.   I am working hard - including fairly low-level equation formatting - to make it look good, and I know you will be changing a lot of that: but those edits are there as part of my style, and I hope I can take a look at the changes you make as you go along.

   Which brings me to an actual question:  attached below is the book.log file from a fairly advanced version of the manuscript, though it is by no means complete, and includes junk appendices at the end  (Part 7, pp 514 - end) that are unlikely to be retained in the final edit, but I have allowed myself the month of March to reconsider those too-rough chapters.  

 ** So my question is "how does the log file look?"  Do you see any red flags, anything I should take a look at as I get to the next level?   I do see one issue, which I think is from Mathematica-created figures that I use in various chapters, which is the warnings:

     LaTeX Font Warning: Size substitutions with differences
        ( Font)              up to 1.7pt have occurred.
    LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 Should I look for the figures that have this problem and see if this is fixable?   How do I identify the figures that trigger this warning, and what, in fact, are the options (if any) for replacing the troublesome fonts by appropriate non-troublesome fonts of my own choosing, instead of letting LaTeX pick the substitutes?

  Also, recall from  long-ago interchanges that  I had to make some manual changes to my environment that may affect your work, and that we might need to discuss:

    1.  I had to manually edit my natbib.sty file to get it to work properly
    2.  We changed the margins in the Elsevierp04 style in order to get my long equations to fit better on the page
    3.  We had to manually edit my LaTeX distribution because I ran out of symbol space in the very first attempt at running the Elsevier p04 style, and so I am depending on those extended variable allocation spaces in order to get LaTeX to run at all.
        Presumably you can verify at least a few of these manual environment changes in the book.log file, and that is part of the reason I am sending it to you this early so you can identify potential snags.

    Thanks, stay safe,
       Andy
       hansona@indiana.edu
     URL: http://homes.sice.indiana.edu/hansona

[book.log](https://github.com/vtex-soft/texsupport.elsevier-book/files/10717115/book.log)

Note: I attempted to attach also the book.pdf file, but it says: Files size too big, 38MB,
only up to 25MB allowed.  And also the header.tex file (to show special constructs I am using) but it refuses that file type, and it also refuses the natbib.sty file type.

**Comment by dgalcius** [comment]
Hi, I will look into it.

**Comment by dgalcius** [comment]
Hi, Andy, 

Let us address technical issues:
1. Warnings are printed at the end of the book.log

```
 LaTeX Font Warning: Size substitutions with differences
    ( Font)              up to 1.7pt have occurred.
LaTeX Font Warning: Some font shapes were not available, defaults substituted. 

```

https://texfaq.org/FAQ-fontunavail

These are accumulated warnings that are printed if during the LaTeX run
there were some font size or shape substitutions.
E.g., on line 2039 there is a message

```
LaTeX Font Info:    Font shape `T1/ntxtlf/bx/n' in size <10> not available
(Font)              Font shape `T1/ntxtlf/b/n' tried instead on input line 275.
```
This is due a font shape substitution *bx* (extra bold) to *b* (bold)

or
```
LaTeX Font Warning: Font shape `OML/cmm/m/it' in size <5.5> not available
(Font)              size <5> substituted on input line 1210.
```
This is due a font size 5.5pt replace with 5pt

or
```
LaTeX Font Warning: Font shape `T1/zi4/m/it' undefined
(Font)              using `T1/zi4/m/n' instead on input line 1340.
```
This is due an italic font substituted with roman. It might be an
error, but probably not in this case unless you do want monospaced italic font shape.

You would get the warning in an instance like `\textit{text \texttt{code} text}` where
there are no monospaced italic font available. An alternative way would be
`\textit{text} \texttt{code} \textit{text}`.

2. Should I look for the figures that have this problem and see if this is fixable?

LaTeX warnings for font shape and size substitutions do not come from figure files (eps).
LaTeX does not process EPS, but rather extracts bounding box 
and reserves space on page for figure file to be included. 
The dvips driver is the one that actually does a job
of including eps figures in postscript file.
LaTeX can complain about not finding bounding box only.

As long as your pdf output is ok, no figures should be fixed.

I'll write you about other issues directly. 
Thank you and best regards, - deimi
