### ISSUE TITLE
Consistency of Figure references?

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#26]
A quick question, I think too technical to ask my editor:
As I read through the manuscript, I notice that I am consistent
with equations, always using the macro \Eqn{name.eq} inline,
and Equation \ref{name.eq} at the beginning of a sentence.

However Figures do not fare so well, and about half the chapters
use a similar macro \Fig{name.fig}, and half written out "Figure \ref{name.fig}"
making it much more work for the formatting team to change the convention
simply by changing the macro.

  Should I go through now and change all the "Figure ..."  to "\FIg{}"?

\newcommand{\Eqn}[1]{Eq.~(\ref{#1})}
\newcommand{\Fig}[1]{Fig.~(\ref{#1})}
%%  \newcommand{\Eqns}[1]{Eqs.~(\ref{##})}  -- doesn't work, do multiples by hand.

**Comment by dgalcius** [comment]
Please make the **output** consistent, either "Figure X" or "Fig. X". It doesn't matter much if it is a macro or plain text in the **source**.
(Consistency in the source files would be fine too.)
