### ISSUE TITLE
Quick one:  page parity?

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#27]
To the best of my knowledge, the Elsevier book style should be starting 
chapters on odd numbers, that is the right hand side of an open book.
When I print the whole book for hand editing, the chapters DO start on odd numbers,
but they PRINT that page on the LEFT, which is wrong.  I tried adding dummy
pages in the front-matter, and no matter what I add, it always adds enough
blank pages so the Chapter first pages print on the LEFT when the pdf is
sent to a laser printer.   What is going wrong?

Here is what book.tex looks like:

\begin{document}

\Frontmatter
%%  \include{cover}
   \include{titlepage}  %%  cover following suggestion by Deimantas
   
  \include{dedication}
  \tableofcontents
  \newpage   %  with or without this, get same result
  \include{preface}
  \include{aboutauthors}

%% This padding fails to get chapters to print title on odd pag)
%   \include{blank}
 
 %%%%%%%%%%  Main  %%%%%%%%%
\Mainmatter

  \include{part1}

  \include{basicintro}
  
  \include{basics}              %%  The "theme" of the book...
 
etc etc etc

===========

Thanks, Andy

**Comment by dgalcius** [comment]
Maybe inserting `\cleardoublepage` would help, but it doesn't matter at this stage. Production will take care of Elsevier book style. - best, deimi
