### ISSUE TITLE
A minor figure arrangement question

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#28]
HI again -
   I have found several figures that are basically half-page width, and instead
of taking a whole page width, I want to arrange two or even three side-by-side.
But with the google keys I tried,  I only found tips for SUBfigures arranged this
way, with ONE shared caption and ONE figure number.  e.g
https://latex-tutorial.com/subfigure-latex/
   I want SEPARATE captions and UNIQUE figure numbers for the side-by-side.  They
don't seem to want to go side by side without a struggle, and when I try 
something  like "minipage", it says that figures are a floating environment, and
forbidden from being controlled by minipage.   This must be a common author
request, but I can't find a good  answer in my Google searches --my answers are 
dominated by single-caption instructions.  How would you do this?

Thanks, Andy

**Comment by dgalcius** [comment]
Hi, please use `{minipage}` environment inside `{figure}`. 
E.g., 

    \begin{figure}
    \begin{minipage}{.45\textwidth}
    \centering
    \includegraphics[width=.45\textwidth]{figure01}
    \caption{<figure1 caption>}
    \end{minipage}
    \hfill
    \begin{minipage}{.45\textwidth}
    \centering
    \includegraphics[width=.45\textwidth]{figure02}
    \caption{<figure2 caption>}
    \end{minipage}
    \end{figure}
