### ISSUE TITLE
Email Address and Corresponding Author 

### ISSUE THREAD

**Issue by Danialesm** [vtex-soft/texsupport.elsevier-book#3]
Hi,
How can I distinguish the corresponding author and add email addresses for multiple authors? 

Thanks

**Comment by dgalcius** [comment]
Hello @Danialesm 

1. The corresponding author can be indicated as a footnote (`\footnote{Corresponding author.}`)
2. E-mail addresses can be indicated as footnotes as well. Alternatively, you can set an email address as 
a regular address with some id, as e.g.: `\address[id=email-ID]{some@email.com}` and indicate to which authors it belong `\author[addressrefs={...,email-ID}]`.

**Comment by Danialesm** [comment]
I am using this code but when I set the footnote it gives an error.
\begin{aug}
   \setcounter{augtemp}{0}
   \author[addressrefs={ad1}]{\fnm{Danial} \snm{Esmaeili Aliabadi\footnote{Corresponding author.}}}
   \address[id=ad1]{Sabanci University Istanbul International Center for Energy and Climate, Istanbul, Turkey}
\end{aug}
Error: 
Overfull \hbox (6.57045pt too wide) in paragraph at lines 3--3
|\T1/qhv/b/n/22 Modelling, sim-u-la-tion and de-ci-sion
! Misplaced \crcr.
\endarray ->\crcr 
                  \egroup \egroup \gdef \@preamble {}\CT@end 
l.19    \and
            
?

**Comment by Danialesm** [comment]
Thanks. It is working now.
