### ISSUE TITLE
"struggling" LaTeX warnings?

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#31]
Hi - I'm getting into the final editing and formatting stages, and thought I would ask
about a LaTeX warning I've been getting:   Is this anything I should take action
about?  Rerender some figures with different software or ???
The QuatRot*.eps figures are screen shots from a piece of interactive graphics
software, and my iMac grabs them initially as .png, the default software to open
it is Preview, and then I save it as a .pdf, and run ps2pdf to get the .eps (I am
using TeXShop "TeX plus dvi", which needs all .eps graphics).  "convert" will
also do pdf->eps I think, but I have been using ps2pdf.   I have little knowledge
of my options for pdf->eps if I should be using some other application to make
life easier for you at VTeX for these images of mine.   Advice and suggestions
welcome.

   Thanks, Andy

...
...
</usr/local/texlive/2017/texmf-dist/fonts/type1/public/fira/FiraSans-Light.pfb>
</usr/local/texlive/2017/texmf-dist/fonts/type1/public/mathabx-type1/matha9.pfb>
</usr/local/texlive/2017/texmf-dist/fonts/type1/public/mathabx-type1/matha7.pfb>
[0<./00CoverImages/Elsevier-Visualizing-More-Quaternions-2.eps>] [1] [2] [3] 
[4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15
<./img/480px-CalabiYau5.eps>] [16] [1] [2] [3] [4] [5<./img/Hamilton.eps>] 
[6<./img/AJH-on-BroomeBridge.eps>] [7] [8] [9] [10] [11] [12] [13] [14] [15] 
[16] [17] [18] [19] [20] [21<./imgKlein/imgA5-1.eps><./imgKlein/imgD6-1.eps>
<./imgKlein/imgTet-1.eps><./imgKlein/imgOcta-1.eps><./imgKlein/imgIco-1.eps>] 
[22<./imgKlein/KleinIJKS2.eps><./imgKlein/KleinS2.eps>] [23] [24] [25
<./imgKlein/S2XToxyPlane1.eps><./imgKlein/S2YToxyPlane1.eps>
<./imgKlein/S2ZToxyPlane1.eps><./imgKlein/S23DToxyPlane1.eps>] [26] [27
<./imgDual/cliffRfl.eps><./imgDual/cliffRotWangle.eps>] [28] [29
<./imgKlein/SimpleS3Triple.eps>] [30] [31] [32] [33] [34] [35
<./img2/S1hemiTripleN.eps><./img2/S1hemiTripleEq.eps>
<./img2/S1hemiTripleS.eps><./img2/S1hemiTripleEqBand.eps>] [36] [37] [38
<./img2/S1Density1.eps>] [39] [40<./imgBasics/S2hemispheres.eps>
<./imgBasics/S2vis.eps><./imgBasics/S2proj.eps>] [41<./img2/arctanDx.eps>] 
[42] [43<./img2/S2Density1a.eps>] [44<./img2/S2Density1b.eps>
<./img2/S2Density1c.eps>] [45<./img2/out3DShells.eps>] [46] [47
<./img2/QuatRot1.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
<./img2/QuatRot2.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
] [48<./img2/QuatRot3.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
<./img2/QuatRot4.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
] [49] [50<./imgBF/S3south.eps><./imgBF/S3eqtr.eps><./imgBF/S3Vis.eps>] [51] 
[52<./imgKlein/SimpleS3Triple.eps>] [53<./imgKlein/WXYS3Triple.eps>] [54
<./imgKlein/IcosaQuatGroup120-v1.eps>] [55<./imgKlein/S3TripleRandom.eps>] 
[56<./imgKlein/fig3DFrmRefVisCh.eps>] [57] [58<./imgBasics/rollingball3D.eps>] 
[59] [60<./imgBasics/SpinAction.eps>] [61<./imgBasics/rollingball4D.eps>] 
[62] [63] [64] [65] [66<./img2/TheNSpheres.eps>] [67] [68
...
...

**Comment by dgalcius** [comment]
Hi, 
These "struggling" warnings are from dvips, not LaTeX. 
If the pdf output is ok, then you should do nothing.
 
Alternatively you might want to fix "faulty" EPS files with `ps2eps` or some similar utility.
Or, a better way,  convert PNG files into EPS with `pngtopnm file.png | pnmtops > file.eps`.
