### ISSUE TITLE
model p04, Appendix in TOC

### ISSUE THREAD

**Issue by ChrisWanah** [vtex-soft/texsupport.elsevier-book#32]
I am using the p04 model, and found an issue with the TOC. 

I have two appendices, A & B. However, in the compiled TOC, it appears
Chapter A
Appendix B

while what I expect is
Appendix A
Appendix B

Thank you. 
![image](https://user-images.githubusercontent.com/132631208/236363984-25fde024-8e44-4f83-9d30-8cadd027d1b5.png)

**Comment by dgalcius** [comment]
Thank you for the issue report. I'll look into it.

**Comment by dgalcius** [comment]
Hi, - I've updated the class files. Please update your ./sty/*.cls files from 
https://github.com/vtex-soft/texsupport.elsevier-book/tree/master/sty/
This should fix the issue.  

best, - deimi

**Comment by ChrisWanah** [comment]
It works now!! Fantastic!!
