### ISSUE TITLE
Wiki citation formats - unsure about them

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#33]
Hi - I am putting final touches on Elsevier "Visualizing More Quaternions", and there are several cases in which clear textbook descriptions of a topic or equation are simply non-existent, so I cite a number of excellent Wikipedia sources.  In order to put these in bibtex, I have used the online utility:   https://irl.github.io/bibwiki/  which appears to produce reasonable entries of the form

@misc{wiki:HurwitzAlgebra,
origtitle = {wiki:Hurwitz's_theorem_(composition_algebras)},
   author = "Wikipedia",
   title = {{Hurwitz's theorem (composition algebras)} --- {W}ikipedia{,} The Free Encyclopedia},
   year = "2023",
   howpublished = {\url{http://en.wikipedia.org/w/index.php?title=Hurwitz's\%20theorem\%20(composition\%20algebras)&oldid=1164729916}},
   note = "[Online; accessed 31-July-2023]",
 }

However, the  pure ascii codes for special characters, even for the space "%20", are not typeset, but remain in the special character ascii code.   I don't think that is what is intended for the Reference bibliography appearance.  Attached are the two pages of the book.pdf containing these citations.

Can we do something to make these have a more useful and appealing formatting?

Thanks, Andy Hanson
 
[wikiBibFmtIssue.pdf](https://github.com/vtex-soft/texsupport.elsevier-book/files/12328102/wikiBibFmtIssue.pdf)

**Comment by dgalcius** [comment]
Hi, 
Option 1: 
Use option "`obeyspaces`" for {url} package and replace` \%20` with `" "` (space)

`\url{http://en.wikipedia.org/w/index.php?title=Hurwitz's~theorem (composition algebras)&oldid=1164729916}`

Option 2:
Using {hyperref} package:
replace `\url{}` command with `\href{}{}`. Replace  `\%20` with `" "` (space) and escape `&` in second argument

`\href{http://en.wikipedia.org/w/index.php?title=Hurwitz's theorem (composition algebras)&oldid=1164729916}{\texttt{http://en.wikipedia.org/w/index.php?title=Hurwitz's theorem (composition algebras)\&oldid=1164729916}}`
