### ISSUE TITLE
"struggling on" warnings

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#34]
Hi - thanks for the note on Wikipedia citations.   I am still not really satisfied with how those show up.
For some time, it was discouraged to use Wiki citations in publications, but there is SO little original source material
on the Web, that is accessible to the average reader, for these subjects, that it is becoming more
acceptable to take advantage of Wiki.   I think it is important for my readers to have these Wiki citations clearly available to
get more details.  But I'm not satisfied with the .bib file entries I am using, or how they appear 
so verbosely in the text.   We and the editors can correspond more on this in production.  Just a heads up.

So, I am doing whole-book passes now, trying to get everything in order for submission around Sept 4,
and I am getting these errors for images I took as MacOS screen shots, converted to pdf, then to eps.
I've used the same process with no problems for years, but here is what I get for these four images:

 [44] [45<./img2/QuatRot1.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
<./img2/QuatRot2.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
] [46<./img2/QuatRot3.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on
<./img2/QuatRot4.eps>
/Library/TeX/texbin/dvips:  expected to see %%EndBinary at end of data; struggling on

I tried to give you the actual .eps files, but GitHub refuses.   Here are the source .png screenshots
that give the .eps files with the above error messages.

Best, Andy

![QuatRot1](https://github.com/vtex-soft/texsupport.elsevier-book/assets/13339899/5b807caa-54ec-4500-9401-94656759471c)
![QuatRot2](https://github.com/vtex-soft/texsupport.elsevier-book/assets/13339899/992a234c-98de-483f-babd-e3fc5785ac57)
![QuatRot3](https://github.com/vtex-soft/texsupport.elsevier-book/assets/13339899/038d7ba4-98ed-4ece-aa63-6bb1bc97f9f4)
![QuatRot4](https://github.com/vtex-soft/texsupport.elsevier-book/assets/13339899/93e6d097-b279-409d-ab6d-5ea3c2e0a122)

**Comment by dgalcius** [comment]
Hi, 
One option would be to do nothing (if the PDF output is OK) 
or you could try to fix EPS files with utilities like e.g.  `purifyeps`  and `pstoedit` 
or you could try to convert PNG files to EPS with tools like  `pngtopnm` and `pnmtops` 
(`cat foo.png | pngtopnm  | pnmtops > foo.eps`)
or you could try to convert via PDF: PNG -> PDF -> EPS.  

best, deimi
