### ISSUE TITLE
Spellchecking?

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#36]
Hi - OK, I solved the "get only the used-image file name list" issue by noticing the data were in the .log file.
Now I am trying to do a document-wide spell check.  checking the 40 individual .tex files is a huge pain
because of all the latex macros that confuse the emacs ispell process, plus having to run each .tex file separately.
    I found a post that said Adobe would check the PDF file, - yes! - getting rid of all the LaTeX macro
confusion!  Except - boo -- it was wrong.  Adobe only checks the note spelling, not the 600 pages
of pdf words' spelling.
   Any ideas about something that would check the WHOLE pdf document spelling in one go?  Also,
I am editing typos etc., something could change accidentally, and I'd need to run spell check again,
and being able to do it just in the pdf would make that trivially easy to redo the spell check.

Thanks, Andy

**Comment by dgalcius** [comment]
Hi, - I do not have any good suggestions. 

What I would do perhaps, convert pdf file to txt format
(e.g., pdftotext or Adobe Acrobat can do that -  but different programs
would produce different results)
and run ispell on txt file.
The txt file will not be very clean for spelling. There will be 
quite some spelling "false positives" but hopefully one can
live with that. 
One more thing that I would personally do: - I would
split PDF into smaller PDF chunks (say, chapters: with \includeonly{chapter01}, ... ) 
and work with smaller chunks of text. 
Version control (e.g. git) can be used for accidental changes 
management. A quick diff for different commits would give you a list of 
changes - wanted and unwanted.  

best, - deimi
