### ISSUE TITLE
Guideline for formatting pass through manuscript for "Visualizing More Quaternions"

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#37]
Hi - too bad no easy spellcheck, but I've found a technique that's tedious, but seems to be finding most of the spelling issues.
What I'm doing now, preparing to send in the book manuscript to Elsevier sometime in the next week or so, is the margins.
   I just remembered the option:  (recall you worked with me to get  wider exceptional frame on top of the P04 so my
long equations would fit)
      \geometry{body={143.757mm,185.737mm},showframe} 
  I thought I had done a pretty good job of getting everything in the margins, and for the EQUATIONS, I did really well,
found only 6 equations to fix outside the margins, easy to do.   However, I noticed that nearly EVERY equation that is at
the BOTTOM, the last thing on a page, spills over the bottom 'showframe' edge by EXACTLY one-half a typeset line.
   Besides the equations,  to my surprise, I found about 75 FIGURES that ran over the "showframe" margins, many 
on the upper edge, but pretty much all over the map.  

    So my questions to you are:  if I have time after finishing the editing and polishing before I need to turn it in:
     1.  Do I need to worry about the 100 pages with a half-line of equation symbols going beyond the bottom margin?
             (I do not actually KNOW how to fix that!)
     2.  Do I need to go back and reformat (mostly changing \includegraphics[width=3.8 in]{epsfilename} to [3.6in], etc)
            all 75 figures until they meet the margin specs?

Thanks, Andy

**Comment by dgalcius** [comment]
Hi - you do not need to worry about these issues. 
The first item is not an issue: it's by design.  
We will take care of text-width-wide  figures at production stage.

best,  - deimi
