### ISSUE TITLE
Fixing Wiki bibitems with [obeyspaces]{url} introduces new anomaly

### ISSUE THREAD

**Issue by andjorhanson** [vtex-soft/texsupport.elsevier-book#38]
Hi - package 'hyperref' could not be used because it redefined  "\C" which I use to denote the
complex number field, and altering all those instances is liable to lead to typos and errors I might not catch.
So I used \usepackage[obeyspaces]{url}, and it seems to work OK, changing

@misc{ALTwiki:Kabsch_algorithm,
   author = "Wikipedia:Kabsch",
   title = "{Kabsch algorithm} --- {W}ikipedia{,} The Free Encyclopedia",
   year = "2018",
   howpublished = {\url{http://en.wikipedia.org/w/index.php?title=Kabsch\%20algorithm\&oldid=838166818}},
   note = "[Online; accessed 22-August-2018]"}
to
@misc{ALTwiki:Kabsch_algorithm,
   author = "Wikipedia:Kabsch",
   title = "{Kabsch algorithm} --- {W}ikipedia{,} The Free Encyclopedia",
   year = "2018",
   howpublished = {\url{http://en.wikipedia.org/w/index.php?title=Kabsch algorithm\&oldid=838166818}},
   note = "[Online; accessed 22-August-2018]"}

Except that now in the PDF bibliography, it inserts MANY spaces, not one, so the reader of a paper copy would not immediately understand what the actual number of spaces in the URL was supposed to be:

Wikipedia. Kabsch algorithm — Wikipedia, the free encyclopedia. 
http://en.wikipedia.org/w/index.php?title= Kabsch      algorithm&oldid=1154985301, 2023k. [Online; accessed 31-July-2023].
Wikipedia. Hurwitz’s theorem (composition algebras) — Wikipedia, the free encyclopedia. http://en.wikipedia.org/ w/index.php?title=Hurwitz’s     theorem     (composition    algebras)&oldid=1164729916, 2023j. [Online; accessed 31-July-2023].

HOWEVER,  very very strangely, when I COPY out of the pdf file, which prints with multiple spaces as above,
it PASTES BACK into this email with single spaces!   So I am not certain what I should do before I turn in the book
on Sept 18 to fix this ??

  Wikipedia. Hurwitz’s theorem (composition algebras) — Wikipedia, the free encyclopedia. http://en.wikipedia.org/ w/index.php?title=Hurwitz’s theorem (composition algebras)&oldid=1164729916, 2023j. [Online; accessed 31-July-2023].

Best, Andy

**Comment by andjorhanson** [comment]
Oh wow ---  when it inserted my text into your Issue text above,  it DELETED the extra spaces I inserted in the two
copied bibitems (Kabsch and Hurwitz) after "what the actual number of spaces in the URL was supposed to be:"
So you can't see what I see in the pdf, which is a zillion extra spaces everywhere I replaced \%20 by  a single
typed <space>.

**Comment by dgalcius** [comment]
Hi, - leave it as it is. As long as an input is correct, we can deal with it.
