### ISSUE TITLE
Changing vertical spaces between lines

### ISSUE THREAD

**Issue by Danialesm** [vtex-soft/texsupport.elsevier-book#4]
Hi, I would like to change the space between lines since most Drafts should be double spaced. Is there any way to change the vertical spaces between lines since I cannot use packages?

Thanks

**Comment by Danialesm** [comment]
I added **\RequirePackage{setspace}** to the sty file and use **\doublespacing** before **\begin{document}**. Now, paragraphs are double spaced.

**Comment by dgalcius** [comment]
Hi @Danialesm, 
Just wondering ...
Why do you say you cannot use packages?

**Comment by Danialesm** [comment]
I cannot use **\usepackage** in the book.tex and instead, I should use **\RequirePackage** in the sty file.
