### ISSUE TITLE
Usage permissions?

### ISSUE THREAD

**Issue by ebruneton** [vtex-soft/texsupport.elsevier-book#40]
Can I use this template to create a PDF freely available on the Internet, which will NOT be published by Elsevier?

**Comment by dgalcius** [comment]
Yes, you can use it.

**Comment by dgalcius** [comment]
I have checked with my manager. And here's a clarification: the template can be used (under the terms of the LPPL licence), as for the similarity of the book's layout to other Elsevier publishing products, you should contact their support: 
https://www.elsevier.com/support
