### ISSUE TITLE
Table of contents with more than 9 chapters

### ISSUE THREAD

**Issue by Rudi000** [vtex-soft/texsupport.elsevier-book#44]
We plan to have more than nine chapters in our book. In the table of contents, the chapter number is aligned on the left instead of the right (see the example below). 
Is there away to fix this? 

![Screenshot 2024-09-10 140359](https://github.com/user-attachments/assets/8df4a758-0c9b-416b-ad75-c15d6f208491)

**Comment by dgalcius** [comment]
Thank you for the issue report. I will look into it.

**Comment by dgalcius** [comment]
Please update your class files from https://github.com/vtex-soft/texsupport.elsevier-book/tree/master/sty (your 
project subfolder ./sty)

Set in preamble (before \begin{document}) 
e.g., \tocsetup{chapternumwidth=16pt} to increase the space reserved for chapter number. 
16pt is arbitrary number. You can use choose whatever you like.

best regards, - deimi

**Comment by Rudi000** [comment]
Thank you. This worked.
