### ISSUE TITLE
\Bbbk already defines

### ISSUE THREAD

**Issue by sgautam71** [vtex-soft/texsupport.elsevier-book#5]
LaTeX Error: Command `\Bbbk' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.261 ...ol{\Bbbk}           {\mathord}{AMSb}{"7C}

?

**Comment by sgautam71** [comment]
i commented out the line but still this

**Comment by dgalcius** [comment]
Which TeXLive version are you using?

**Comment by dgalcius** [comment]
I fixed the issue. Thanks.

**Comment by sgautam71** [comment]
thankyou

I liked the package, it is perfect
Do you have a similar for Phd/master thesis too... a general one university
independent

it will be a great favor

warm regards

Dr. Sanjeev Gautam
Assistant Professor
Dr. SSB Univ
ersity
 Institute of
Chemical Eng
ineering
 & Technology,
(
Formally known as  Department of Chemical Engineering
)
Panjab University, Chandigarh -160014, India
http://orcid.org/0000-0003-3123-9906

**Comment by dgalcius** [comment]
I am sorry, I do not have any phd/master thesis templates. 
But perhaps you can find one on  https://www.latextemplates.com/cat/theses or on https://www.overleaf.com/gallery/tagged/thesis/ that can fit your needs.
Best regards, 
Deimantas Galčius

**Comment by sgautam71** [comment]
thanking you for your kind support

sanjeev

Dr. Sanjeev Gautam
Assistant Professor
Dr. SSB Univ
ersity
 Institute of
Chemical Eng
ineering
 & Technology,
(
Formally known as  Department of Chemical Engineering
)
Panjab University, Chandigarh -160014, India
http://orcid.org/0000-0003-3123-9906

**Comment by sgautam71** [comment]
need your help, in case the book is edited by editors and different chapters are added by different authors
so that in each chapter the following can be added
-------------
\begin{frontmatter}

\chapter{Photovoltaic behavior of ferrites}\label{chap1}
\subchapter{Chapter Subtitle}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\author[aff1]{author firstname sirname}
\author[aff2]{author firstname sirname}
\author[aff1]{author firstname sirname}
\address[aff1]{Department of Physics, Panjab University, Chandigarh - 160 014, India}
\author[aff2]{author firstname sirname\corref{cor1}}
\address[uicet]{Advanced Functional Materials Lab., Dr. S. S. Bhatnagar University Institute of Chemical Engineering \& Technology, Panjab University, Chandigarh, 160014, India}
\ead{usernameATunversity.ac.in}\cortext[cor1]{Corresponding author: Phone/Fax: ++91-xxxx-xxxxx}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \minitoc

please guide

**Comment by sgautam71** [comment]
I add that I use pdftex in miktex latest version

**Comment by dgalcius** [comment]
I'm not sure I understand your question.  

The template's coding for authors is provided in chapter2.tex.
Please follow it. Alternatively, if you have already set chapters in some
other template or class, it is fine. You do not have to rekey your chapters.

**Comment by sgautam71** [comment]
thanks,  i see that in chapter 2, and it is perfect

How about running pdflatex?
It is perfect with latex and makes DVI ? but gives error in dvi2pdf (return nozero Exit Code(1) )
Wish it could run with pdflatex (i am using winedt/Miktex)

**Comment by dgalcius** [comment]
pdflatex should be just fine.
