### ISSUE TITLE
Acknowleddgment

### ISSUE THREAD

**Issue by virsto** [vtex-soft/texsupport.elsevier-book#6]
How to get acknowledgments in downloaded **elsevierbook.cls** ?

**Comment by dgalcius** [comment]
If it's meant for a whole book then please use `\chapter*`:
```
\begin{frontmatter}
\chapter*{Acknowledgments}
\end{frontmatter}

```

If it's meant for a chapter then please use `ack` or `acks` environment:
```
\begin{acks}
  Text ...
\end{acks}
```
