### ISSUE TITLE
Structure for an Elsevier scientific book

### ISSUE THREAD

**Issue by virsto** [vtex-soft/texsupport.elsevier-book#7]
Please provide a PDF that shows the structure that should be used for an Elsevier scientific book. **For example**:
  

- Front Matter
     Title
     Dedication 
     Preface
     Foreword
     Acknowledgments
     Table of contents
- Text Body
    Chapters
    . . .
    . . .
    . . .
- Back Matter
    Appendices
    Glossary
    Index

**Comment by dgalcius** [comment]
I cannot. It's up to the author(s)/editor(s) to use whatever book structure suits best for a project.
