### ISSUE TITLE
Figure caption with title

### ISSUE THREAD

**Issue by Dana-L** [vtex-soft/texsupport.elsevier-book#9]
Earlier versions of the Elsevier book style had a very useful option of having a figure caption title, or header, in the same line of the figure number (e.g., "FIGURE 1.3      Figure caption title"), above the ordinary figure caption, in bold. This option was defined in the file "elsbook.cls" as 
\def\FIG#1#2{\centering#1#2}
\newenvironment{FIG*}{\centering}{}

However, I cannot find such an option in the more recent versions of the Elsevier book style. In the new versions, to the best of my understanding, figures and their captions can only be defined used the traditional 
\begin{figure}
\includegraphics{figure_file_name}
\caption{Figure caption}
\end{figure}

My question: is it possible to add an option of a figure caption title in the upcoming Elsevier book templates? The same goes for table captions.

**Comment by dgalcius** [comment]
Thank you for the issue report. I'll see into it.

**Comment by dgalcius** [comment]
I've added \title command for figure/table caption. Please note the command \title should precede  the \caption command. 

\begin{figure}
\title{}% Figure title
\caption{}% Figure caption
\label{}%
\end{figure}

\begin{table}
\title{}% Table title
\caption{}% Table caption
\label{}%
\end{table}
